spring.application.name=audit-portal
server.port=9080
spring.datasource.url=jdbc:postgresql://ep-odd-cell-an5e3qq2-pooler.c-6.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Dd0J5bhOQTys

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
logging.level.org.springframework.security=DEBUG
spring.app.jwtSecret=VGhpc0lzQVN1cGVyU2VjdXJlSldUU2VjcmV0S2V5Rm9ySFMyNTY=
spring.app.jwtExpirationMs=60000000
spring.app.jwtRefreshExpirationMs=3000000
spring.app.CHAR_POOL=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%&*

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

azure.storage.connection-string=${AZURE_STORAGE_CONNECTION_STRING}
azure.storage.container-name=audit-files

azure.servicebus.connection-string=${AZURE_SERVICE_BUS_CONNECTION_STRING}
azure.servicebus.queue-name=pdf-parsing-queue
azure.servicebus.result-queue-name=pdf-parse-result

spring.app.frontend.url=http://localhost:3000